### ISSUE TITLE
Добавить бейджики Travis CI и CodeCov

### ISSUE THREAD

**Issue by coursar** [rustamSurmashev/spendSaver#1]

**Comment by rustamSurmashev** [comment]
@coursar, lib.js исправлен в cd13f84b1a5154adfe67f9a148b136fcb34caf67
начинаю заниматься app.js

**Comment by rustamSurmashev** [comment]
@coursar, добрый день.
Застрял на создании app.js в 3e21150d6ed5e77513ee241de8617796d7aced78
Я решил в этом файле реализовать 2 задачи:
1. загрузка новых элементов в массив
2. вызов функций из lib.js
Но уже на первой стадии "забуксовал".
Сейчас в браузере в console выходит такая ошибка: "Uncaught TypeError: Cannot read property 'addEventListener' of null at app.js:13"... 
Мне пытаться дальше эти 2 задачи решить или я в принципе не тот подход использую?

**Comment by rustamSurmashev** [comment]
@coursar , по результатам дополнительной пары 19.01.2019 мной принято решение переписать вообще всё. Поэтому пока закрываю это эссью.
