### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by rustamSurmashev** [rustamSurmashev/spendSaver#4]
@coursar , возникли следующие проблемы:
1. Не могу придумать функцию, которая считает сумму (видимо изначально не тот подход выбирал)
2. Аналогичная ситуация с определением максимального значения
3. Соответственно и автотест не могу написать
4. Для заливки на TravisCI пришлось удалять из файла package.json строки с отсылками на тест и тест-коверэйдж (ну это поправимо после написания теста).

Подскажите пожалуйста... 
.reduce?
или обычная функция в lib.js?
Заранее спасибо!

**Comment by coursar** [comment]
это обычная функция-метод в lib.js
